[licenses]
version = 2
allow = [
  "MIT",
  "Apache-2.0",
  "Unicode-DFS-2016",
  "Unicode-3.0",
  "MPL-2.0",
  "WTFPL",
  "Zlib",
]

[advisories]
version = 2
yanked = "deny"
# paste is unmaintained
ignore = ["RUSTSEC-2024-0436"]

[bans]
multiple-versions = "allow"
